"use client";

import { useEffect, useState } from "react";
import {
  Sparkles,
  Check,
  X,
  Pencil,
  Plus,
  RefreshCw,
  AlertCircle,
  Info,
  Loader2,
  Save,
} from "lucide-react";
import type { InsightCategory, InsightSeverity, InsightStatus } from "@prisma/client";

type Insight = {
  id: string;
  engagementId: string;
  category: InsightCategory;
  severity: InsightSeverity;
  status: InsightStatus;
  title: string;
  body: string;
  autoGenerated: boolean;
  sourceMetric: string | null;
  createdAt: string;
  approvedAt: string | null;
};

const CATEGORY_LABEL: Record<InsightCategory, string> = {
  VIDEO: "Vídeo",
  BUDGET: "Orçamento",
  GEO: "Geo",
  HEALTH: "Saúde",
  CREATIVE: "Criativo",
  FUNNEL: "Funil",
  CUSTOM: "Manual",
};

const SEVERITY_STYLE: Record<InsightSeverity, string> = {
  OK: "bg-success/12 text-success",
  WARN: "bg-warning/12 text-warning",
  INFO: "bg-info/12 text-info",
};

const SEVERITY_LABEL: Record<InsightSeverity, string> = {
  OK: "Positivo",
  WARN: "Atenção",
  INFO: "Info",
};

const TABS: { value: InsightStatus; label: string }[] = [
  { value: "PENDING", label: "Pendentes" },
  { value: "APPROVED", label: "Aprovadas" },
  { value: "DISMISSED", label: "Descartadas" },
];

export function InsightsCurationView({ engagementId }: { engagementId: string }) {
  const [tab, setTab] = useState<InsightStatus>("PENDING");
  const [insights, setInsights] = useState<Insight[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [genMsg, setGenMsg] = useState<string | null>(null);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [creatingManual, setCreatingManual] = useState(false);

  async function load() {
    setLoading(true);
    const res = await fetch(
      `/api/portal/insights?engagementId=${engagementId}&status=${tab}`,
    );
    const data = await res.json();
    setInsights(Array.isArray(data) ? data : []);
    setLoading(false);
  }

  useEffect(() => {
    load();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [tab, engagementId]);

  async function generate() {
    setGenerating(true);
    setGenMsg(null);
    const res = await fetch("/api/portal/insights/generate", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ engagementId, datePreset: "last_30d" }),
    });
    const data = await res.json();
    setGenerating(false);
    if (data.error) {
      setGenMsg(`Erro: ${data.error}`);
      return;
    }
    setGenMsg(
      `${data.created} sugestão${data.created === 1 ? "" : "es"} nova${data.created === 1 ? "" : "s"} · ${data.skipped} já existentes puladas`,
    );
    if (tab === "PENDING") load();
  }

  async function updateStatus(id: string, status: InsightStatus) {
    await fetch(`/api/portal/insights/${id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ status }),
    });
    load();
  }

  async function saveEdit(id: string, patch: Partial<Insight>) {
    await fetch(`/api/portal/insights/${id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(patch),
    });
    setEditingId(null);
    load();
  }

  async function createManual(data: { title: string; body: string; category: InsightCategory; severity: InsightSeverity }) {
    await fetch("/api/portal/insights", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ engagementId, ...data }),
    });
    setCreatingManual(false);
    setTab("APPROVED"); // vai pra tab onde a manual acabou de aparecer
  }

  return (
    <div>
      {/* Tabs + actions */}
      <div className="flex items-center justify-between gap-4 flex-wrap mb-5">
        <div className="inline-flex gap-1 p-1 bg-muted rounded-full">
          {TABS.map((t) => (
            <button
              key={t.value}
              onClick={() => setTab(t.value)}
              className={`px-4 py-1.5 rounded-full text-[13px] font-medium transition ${
                tab === t.value
                  ? "bg-card text-foreground shadow-sm"
                  : "text-muted-foreground hover:text-foreground"
              }`}
            >
              {t.label}
            </button>
          ))}
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={generate}
            disabled={generating}
            className="inline-flex items-center gap-2 px-3.5 py-2 bg-brand/10 text-brand border border-brand/25 rounded-full text-[13px] font-medium hover:bg-brand/15 transition disabled:opacity-50"
          >
            {generating ? (
              <Loader2 className="w-3.5 h-3.5 animate-spin" strokeWidth={2} />
            ) : (
              <Sparkles className="w-3.5 h-3.5" strokeWidth={2} />
            )}
            {generating ? "Gerando…" : "Gerar sugestões"}
          </button>
          <button
            onClick={() => setCreatingManual(true)}
            className="inline-flex items-center gap-2 px-3.5 py-2 bg-foreground text-background rounded-full text-[13px] font-medium hover:opacity-90 transition"
          >
            <Plus className="w-3.5 h-3.5" strokeWidth={2} />
            Análise manual
          </button>
        </div>
      </div>

      {genMsg && (
        <div className="bg-muted/60 border border-border rounded-lg px-4 py-2.5 text-[13px] text-foreground mb-4">
          {genMsg}
        </div>
      )}

      {/* Manual creation form */}
      {creatingManual && (
        <ManualInsightForm
          onCancel={() => setCreatingManual(false)}
          onSave={createManual}
        />
      )}

      {/* List */}
      {loading ? (
        <div className="text-center py-12 text-muted-foreground text-[13px]">Carregando…</div>
      ) : insights.length === 0 ? (
        <div className="bg-card border border-dashed border-border rounded-2xl p-14 text-center">
          <div className="w-12 h-12 rounded-2xl bg-brand/10 flex items-center justify-center mx-auto mb-4">
            <Sparkles className="w-5 h-5 text-brand" strokeWidth={1.7} />
          </div>
          <p className="text-[14px] text-foreground font-medium mb-1">
            Nada em {TABS.find((t) => t.value === tab)?.label.toLowerCase()}
          </p>
          <p className="text-[12.5px] text-muted-foreground max-w-md mx-auto">
            {tab === "PENDING"
              ? 'Clique em "Gerar sugestões" pra o sistema analisar os dados atuais e propor observações.'
              : tab === "APPROVED"
                ? "Nenhuma análise aprovada ainda. Aprove as pendentes ou crie uma manual."
                : "Nenhuma análise descartada."}
          </p>
        </div>
      ) : (
        <div className="space-y-3">
          {insights.map((i) =>
            editingId === i.id ? (
              <EditForm
                key={i.id}
                insight={i}
                onCancel={() => setEditingId(null)}
                onSave={(patch) => saveEdit(i.id, patch)}
              />
            ) : (
              <InsightRow
                key={i.id}
                insight={i}
                onEdit={() => setEditingId(i.id)}
                onApprove={() => updateStatus(i.id, "APPROVED")}
                onDismiss={() => updateStatus(i.id, "DISMISSED")}
                onReopen={() => updateStatus(i.id, "PENDING")}
              />
            ),
          )}
        </div>
      )}
    </div>
  );
}

function InsightRow({
  insight,
  onEdit,
  onApprove,
  onDismiss,
  onReopen,
}: {
  insight: Insight;
  onEdit: () => void;
  onApprove: () => void;
  onDismiss: () => void;
  onReopen: () => void;
}) {
  const Icon = insight.severity === "WARN" ? AlertCircle : insight.severity === "OK" ? Check : Info;
  return (
    <div className="bg-card border border-border rounded-2xl p-5">
      <div className="flex items-start gap-4">
        <div className={`w-9 h-9 rounded-lg flex items-center justify-center flex-shrink-0 ${SEVERITY_STYLE[insight.severity]}`}>
          <Icon className="w-4.5 h-4.5" strokeWidth={2} />
        </div>
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-1 flex-wrap">
            <span className={`text-[10px] uppercase tracking-[0.08em] font-bold px-2 py-0.5 rounded-full ${SEVERITY_STYLE[insight.severity]}`}>
              {SEVERITY_LABEL[insight.severity]}
            </span>
            <span className="text-[11px] text-muted-foreground font-medium bg-muted px-2 py-0.5 rounded-full">
              {CATEGORY_LABEL[insight.category]}
            </span>
            {insight.autoGenerated ? (
              <span className="text-[10.5px] text-brand/80">gerado pelo sistema</span>
            ) : (
              <span className="text-[10.5px] text-brand/80">análise manual</span>
            )}
          </div>
          <h4 className="text-[15px] font-semibold text-foreground tracking-tight leading-tight mb-1">
            {insight.title}
          </h4>
          <p className="text-[13px] text-foreground/80 leading-relaxed">{insight.body}</p>
          {insight.sourceMetric && (
            <p className="text-[10.5px] text-muted-foreground mt-2 font-mono">
              {insight.sourceMetric}
            </p>
          )}
        </div>
        <div className="flex gap-1 flex-shrink-0">
          <button
            onClick={onEdit}
            className="p-2 hover:bg-muted rounded-lg text-muted-foreground hover:text-foreground transition"
            title="Editar"
          >
            <Pencil className="w-3.5 h-3.5" strokeWidth={1.8} />
          </button>
          {insight.status !== "APPROVED" && (
            <button
              onClick={onApprove}
              className="p-2 hover:bg-success/12 rounded-lg text-muted-foreground hover:text-success transition"
              title="Aprovar"
            >
              <Check className="w-3.5 h-3.5" strokeWidth={2} />
            </button>
          )}
          {insight.status !== "DISMISSED" && (
            <button
              onClick={onDismiss}
              className="p-2 hover:bg-destructive/12 rounded-lg text-muted-foreground hover:text-destructive transition"
              title="Descartar"
            >
              <X className="w-3.5 h-3.5" strokeWidth={2} />
            </button>
          )}
          {insight.status !== "PENDING" && (
            <button
              onClick={onReopen}
              className="p-2 hover:bg-muted rounded-lg text-muted-foreground hover:text-foreground transition"
              title="Voltar pra pendente"
            >
              <RefreshCw className="w-3.5 h-3.5" strokeWidth={1.8} />
            </button>
          )}
        </div>
      </div>
    </div>
  );
}

function EditForm({
  insight,
  onCancel,
  onSave,
}: {
  insight: Insight;
  onCancel: () => void;
  onSave: (patch: Partial<Insight>) => void;
}) {
  const [title, setTitle] = useState(insight.title);
  const [body, setBody] = useState(insight.body);
  const [severity, setSeverity] = useState<InsightSeverity>(insight.severity);

  return (
    <div className="bg-card border border-brand/40 rounded-2xl p-5 space-y-3">
      <input
        value={title}
        onChange={(e) => setTitle(e.target.value)}
        className="w-full px-3 py-2 border border-border rounded-lg text-[14px] font-medium bg-background"
        placeholder="Título"
      />
      <textarea
        value={body}
        onChange={(e) => setBody(e.target.value)}
        rows={3}
        className="w-full px-3 py-2 border border-border rounded-lg text-[13px] bg-background resize-none leading-relaxed"
        placeholder="Corpo da análise"
      />
      <div className="flex items-center justify-between flex-wrap gap-2">
        <div className="flex gap-1.5">
          {(["OK", "WARN", "INFO"] as InsightSeverity[]).map((s) => (
            <button
              key={s}
              onClick={() => setSeverity(s)}
              className={`px-3 py-1 rounded-full text-[11px] font-semibold ${
                severity === s ? SEVERITY_STYLE[s] : "bg-muted text-muted-foreground"
              }`}
            >
              {SEVERITY_LABEL[s]}
            </button>
          ))}
        </div>
        <div className="flex gap-2">
          <button
            onClick={onCancel}
            className="text-[12.5px] px-3 py-1.5 text-muted-foreground hover:text-foreground"
          >
            Cancelar
          </button>
          <button
            onClick={() => onSave({ title, body, severity })}
            className="text-[12.5px] px-3.5 py-1.5 bg-foreground text-background rounded-full font-medium hover:opacity-90 inline-flex items-center gap-1.5"
          >
            <Save className="w-3 h-3" strokeWidth={2} />
            Salvar
          </button>
        </div>
      </div>
    </div>
  );
}

function ManualInsightForm({
  onCancel,
  onSave,
}: {
  onCancel: () => void;
  onSave: (data: { title: string; body: string; category: InsightCategory; severity: InsightSeverity }) => void;
}) {
  const [title, setTitle] = useState("");
  const [body, setBody] = useState("");
  const [severity, setSeverity] = useState<InsightSeverity>("INFO");
  const [category, setCategory] = useState<InsightCategory>("CUSTOM");

  return (
    <div className="bg-card border border-brand/40 rounded-2xl p-5 space-y-3 mb-4">
      <div className="text-[13px] font-medium text-foreground mb-1">Nova análise manual</div>
      <input
        value={title}
        onChange={(e) => setTitle(e.target.value)}
        placeholder="Título — ex: Reformular pauta de novembro"
        autoFocus
        className="w-full px-3 py-2 border border-border rounded-lg text-[14px] font-medium bg-background"
      />
      <textarea
        value={body}
        onChange={(e) => setBody(e.target.value)}
        placeholder="Detalhe o que observou e o que sugere fazer"
        rows={3}
        className="w-full px-3 py-2 border border-border rounded-lg text-[13px] bg-background resize-none leading-relaxed"
      />
      <div className="flex items-center justify-between flex-wrap gap-2">
        <div className="flex gap-1.5 flex-wrap">
          {(Object.keys(CATEGORY_LABEL) as InsightCategory[]).map((c) => (
            <button
              key={c}
              onClick={() => setCategory(c)}
              className={`px-2.5 py-1 rounded-full text-[10.5px] font-medium ${
                category === c ? "bg-brand text-white" : "bg-muted text-muted-foreground"
              }`}
            >
              {CATEGORY_LABEL[c]}
            </button>
          ))}
        </div>
      </div>
      <div className="flex items-center justify-between flex-wrap gap-2">
        <div className="flex gap-1.5">
          {(["OK", "WARN", "INFO"] as InsightSeverity[]).map((s) => (
            <button
              key={s}
              onClick={() => setSeverity(s)}
              className={`px-3 py-1 rounded-full text-[11px] font-semibold ${
                severity === s ? SEVERITY_STYLE[s] : "bg-muted text-muted-foreground"
              }`}
            >
              {SEVERITY_LABEL[s]}
            </button>
          ))}
        </div>
        <div className="flex gap-2">
          <button
            onClick={onCancel}
            className="text-[12.5px] px-3 py-1.5 text-muted-foreground hover:text-foreground"
          >
            Cancelar
          </button>
          <button
            onClick={() => title.trim() && body.trim() && onSave({ title: title.trim(), body: body.trim(), category, severity })}
            disabled={!title.trim() || !body.trim()}
            className="text-[12.5px] px-3.5 py-1.5 bg-foreground text-background rounded-full font-medium hover:opacity-90 disabled:opacity-50 inline-flex items-center gap-1.5"
          >
            <Save className="w-3 h-3" strokeWidth={2} />
            Publicar
          </button>
        </div>
      </div>
    </div>
  );
}
