// AUTO-GERADO da planilha pop_culture_7temas.xlsx (16/mai/2026).
// Conteúdo curado pela Karol/Arthea pro acervo do André.
export const SEED_SCENES = [
  {
    theme: "COMMUNICATION_FAILURE",
    order: 1,
    characters: "Brooke & Gary",
    type: "Filme",
    work: "The Break-Up (2006) · Prime Video",
    context: "Casal que termina mas nenhum quer sair do apartamento compartilhado. O filme inteiro gira em torno desse impasse. O público os conhece como Jennifer Aniston e Vince Vaughn na comédia romântica que não tem final feliz.",
    sceneAndQuote: "Ela diz que quer que ele QUEIRA lavar os pratos. Ele diz que lava. Ela explode. Ele não entende o que está por baixo da frase.\nFala: 'Eu quero que você QUEIRA fazer isso. Não que você faça porque eu pedi.' — Brooke",
    platform: "Prime Video: 'Separados pelo Casamento' — primeira meia hora",
    videoLink: "",
    hook: "Você já pediu algo e a resposta foi 'tá bom'... mas nada mudou?",
    clinicalAngle: "Quando a gente para de pedir o que precisa e começa a esperar que o outro adivinhe, o relacionamento vira um teste que ninguém sabe que está fazendo.",
  },
  {
    theme: "COMMUNICATION_FAILURE",
    order: 2,
    characters: "Charlie & Nicole",
    type: "Filme",
    work: "História de um Casamento (2019) · Netflix",
    context: "Casal de teatro em Nova York em processo de divórcio. Os dois ainda se amam e não conseguem mais ficar juntos. Não há vilão. A cena da briga é a mais comentada do streaming.",
    sceneAndQuote: "Câmera única sem corte. Anos de coisas não ditas chegando ao mesmo tempo.\nFala: 'Às vezes eu acordo desejando que você esteja morta.' — Charlie, antes de chorar no chão",
    platform: "Netflix: 'História de um Casamento'",
    videoLink: "youtube.com/watch?v=lprJ3LAvFbI (legendado PT-BR)\nyoutube.com/watch?v=4J2iCHEF9G4 (dublado PT)",
    hook: "A briga mais feia que você já teve: ela veio do nada ou veio de tudo que não foi dito?",
    clinicalAngle: "Por que a gente diz o pior para quem mais amou? Essa cena não é sobre raiva. É sobre anos de coisas não ditas chegando ao mesmo tempo, sem espaço para serem recebidas.",
  },
  {
    theme: "COMMUNICATION_FAILURE",
    order: 3,
    characters: "Jesse & Celine",
    type: "Filme",
    work: "Before Midnight (2013) · Prime Video",
    context: "Casal romântico dos dois primeiros filmes da trilogia, agora com 9 anos juntos e filhas gêmeas. O público que os amava não esperava ver isso deles.",
    sceneAndQuote: "Jantar tranquilo que termina em briga intensa no quarto do hotel. Jesse racionaliza. Celine sente. Dois jeitos de brigar que não se encontram.\nFala: 'Acho que não te amo mais.' — Celine",
    platform: "Prime Video: 'Antes da Meia-Noite'\nDailymotion: dailymotion.com/video/x7pef2r (completo legendado)",
    videoLink: "dailymotion.com/video/x7pef2r (filme completo legendado — briga: ~1h15min)",
    hook: "'Acho que não te amo mais.' Você sabe a diferença entre desamor e exaustão?",
    clinicalAngle: "O amor não acabou nessa cena. O que acabou foi a capacidade de fazer o outro se sentir visto. Exaustão emocional e desamor têm a mesma cara, mas a solução é completamente diferente.",
  },
  {
    theme: "COMMUNICATION_FAILURE",
    order: 4,
    characters: "Cindy & Dean",
    type: "Filme",
    work: "Blue Valentine (2010) · YouTube / Dailymotion",
    context: "O filme mostra o início apaixonado e o fim desgastado ao mesmo tempo, sem linearidade. O público vê as duas versões do mesmo casal simultaneamente.",
    sceneAndQuote: "No motel, num momento aparentemente tranquilo, Cindy questiona a ambição de Dean. Silêncio. Ela olha através dele, não para ele. Dean não percebe.\nFala: 'Não sei... Não me importo muito com essas coisas.' — Dean, sobre o futuro deles",
    platform: "YouTube (dublado PT): youtube.com/watch?v=bwUgBD9b4Nc\nDailymotion (legendado): dailymotion.com/video/x22ng2w",
    videoLink: "youtube.com/watch?v=bwUgBD9b4Nc (dublado PT — cena: ~55min)\ndailymotion.com/video/x22ng2w (legendado completo)",
    hook: "O distanciamento não grita. Ele aparece quando você percebe que está olhando para ele, mas não o vê mais.",
    clinicalAngle: "Quando foi a última vez que você olhou para ele, não através dele? O distanciamento não é barulhento. É o olhar que passa por cima.",
  },
  {
    theme: "COMMUNICATION_FAILURE",
    order: 5,
    characters: "Meredith & Derek",
    type: "Série",
    work: "Grey's Anatomy T11 · Star+",
    context: "Casal central da série há 11 temporadas. A traição de Derek chocou o público que os acompanhava desde o início.",
    sceneAndQuote: "Depois da traição, cada conversa sobre confiança vira acusação. Os dois falam de dores diferentes sem perceber.\nFala: 'Eu preciso que você confie em mim.' / 'Você me fez escolher entre você e minha carreira.'",
    platform: "Star+: 'Grey's Anatomy' — temporada 11",
    videoLink: "",
    hook: "É possível os dois estarem com razão e mesmo assim ninguém ser ouvido?",
    clinicalAngle: "Quando cada um fala de uma dor diferente na mesma conversa, ninguém é ouvido. Os dois têm razão. E nenhum dos dois consegue chegar no outro.",
  },
  {
    theme: "SILENT_DISTANCE",
    order: 1,
    characters: "Cindy & Dean",
    type: "Filme",
    work: "Blue Valentine (2010) · YouTube / Dailymotion",
    context: "O filme não é linear. O público vê o início apaixonado e o fim desgastado ao mesmo tempo. Os créditos finais voltam para o momento mais bonito do casal, depois de mostrar o fim.",
    sceneAndQuote: "Dean toca ukelele na rua para Cindy dançar. A cena mais bonita do filme acontece no passado. No presente, mal se olham.\nFala: 'Você e eu, você e eu, só você e eu.' — Dean canta para Cindy",
    platform: "YouTube (dublado PT): youtube.com/watch?v=bwUgBD9b4Nc\nDailymotion (legendado): dailymotion.com/video/x22ng2w",
    videoLink: "youtube.com/watch?v=bwUgBD9b4Nc (dublado PT — cena: ~30min)\ndailymotion.com/video/x22ng2w (legendado completo)",
    hook: "Esse casal já foi isso. O que aconteceu no meio que ninguém viu?",
    clinicalAngle: "Como o mesmo casal que teve esse momento chegou onde chegou? O distanciamento não apaga o passado, mas o passado também não salva o presente.",
  },
  {
    theme: "SILENT_DISTANCE",
    order: 2,
    characters: "Jim & Pam",
    type: "Série",
    work: "The Office T9 · Netflix",
    context: "Casal mais querido da série, amigos que viraram casal, casaram e tiveram filhos. O público que os acompanhou desde o início sente a crise da temporada 9 como uma perda pessoal.",
    sceneAndQuote: "Jim está na Filadélfia pela startup. Pam está em Scranton com os filhos. A câmera flagra Pam chorando sozinha no carro depois de uma ligação difícil. Ela seca o rosto antes de entrar em casa.\nFala: 'Eu não sei o que aconteceu com a gente.' — Pam",
    platform: "Netflix: 'The Office' — temporada 9",
    videoLink: "",
    hook: "Você já sentiu solidão dentro do próprio relacionamento?",
    clinicalAngle: "A solidão dentro do relacionamento não precisa de abandono. Às vezes é só dois projetos de vida crescendo em direções diferentes, sem que ninguém tenha decidido isso.",
  },
  {
    theme: "SILENT_DISTANCE",
    order: 3,
    characters: "Sandra & Samuel",
    type: "Filme",
    work: "Anatomia de uma Queda (2023) · Prime Video",
    context: "Samuel morreu e Sandra é julgada pela morte. No tribunal, um áudio revela a briga real do casal. Palma de Ouro e Oscar. Muito comentado no Brasil em 2024.",
    sceneAndQuote: "Áudio da briga reproduzido no tribunal. Dois pontos de vista completamente diferentes do mesmo casamento, e nenhum parece estar mentindo.\nFala: 'Você me apagou. Devagar. Sem perceber que estava fazendo isso.' — Sandra",
    platform: "Prime Video: 'Anatomia de uma Queda'",
    videoLink: "",
    hook: "Você e ele vivem o mesmo casamento, ou dois casamentos completamente diferentes?",
    clinicalAngle: "Um casal pode viver versões completamente diferentes do mesmo relacionamento. O que cada um chama de 'o que aconteceu entre nós' pode ser duas histórias verdadeiras sobre o mesmo casamento.",
  },
  {
    theme: "SILENT_DISTANCE",
    order: 4,
    characters: "Carrie & Big",
    type: "Série",
    work: "Sex and the City · Max",
    context: "Big nunca escolheu Carrie de vez, por anos. O público feminino a acompanhou esperando junto com ela. O revival de 2022 trouxe mulheres 35-50 de volta para revisitar o que normalizaram na juventude.",
    sceneAndQuote: "T2 E18: Big vai para Paris com outra. Carrie percebe sozinha no apartamento que passou anos adaptando as próprias expectativas. Sem palavras, só o rosto dela.\nFala: 'Tudo que eu precisava era de um sinal, qualquer sinal, de que isso era real.' — Carrie",
    platform: "Max: 'Sex and the City' — T2 episódio 18",
    videoLink: "",
    hook: "Você está esperando que ele escolha, ou você já sabe a resposta?",
    clinicalAngle: "O que a gente chama de esperar que o outro amadureça às vezes é a dificuldade de sair de um ciclo que a gente mesmo alimentou. Ela sabia e ficava. Por quê?",
  },
  {
    theme: "SILENT_DISTANCE",
    order: 5,
    characters: "Don Draper",
    type: "Série",
    work: "Mad Men T4 · Prime Video",
    context: "Publicitário de sucesso nos anos 60 com identidade falsa e casamentos que afundam. Incapaz de ser real com quem ama. O público o conhece como o homem que tem tudo e não consegue ser feliz com nada.",
    sceneAndQuote: "T4 E7: Don e Peggy passam a madrugada no escritório. Don chora ao saber de uma morte. O momento mais real que ele já teve foi com a colega de trabalho, não com a esposa.\nFala: 'Você é a única pessoa que conheço que sabe que não me conhece.' — Don para Peggy",
    platform: "Prime Video: 'Mad Men' — T4 episódio 7",
    videoLink: "",
    hook: "Por que é mais fácil ser real com um colega de trabalho do que com a própria esposa?",
    clinicalAngle: "Ele não é incapaz de intimidade. É incapaz com a pessoa errada. Como isso aparece dentro do casamento?",
  },
  {
    theme: "THE_CHOICE",
    order: 1,
    characters: "Nora & Hae-sung",
    type: "Filme",
    work: "Vidas Passadas (2023) · Telecine / Prime Video",
    context: "Nora emigrou da Coreia quando criança. Hae-sung foi o amor que ficou. Eles se reencontram 24 anos depois, ela já casada com um americano. O público os conhece pela indicação ao Oscar e pelo final.",
    sceneAndQuote: "Cena final: Nora despede Hae-sung na rua. Chora. Entra em casa. Deita ao lado do marido. Zero diálogo, tudo no rosto.\nSem fala: só o choro e a escolha de entrar.",
    platform: "Telecine: 'Vidas Passadas'\nPrime Video: 'Vidas Passadas'",
    videoLink: "",
    hook: "Escolher alguém não significa não sentir falta de outro. Você sabia disso?",
    clinicalAngle: "Amor maduro não é amor sem dúvida. É amor que decide mesmo com a dúvida dentro. Não é ausência de sentimento. É presença de escolha.",
  },
  {
    theme: "THE_CHOICE",
    order: 2,
    characters: "Brooke & Gary",
    type: "Filme",
    work: "The Break-Up (2006) · Prime Video",
    context: "Casal que não conseguia se comunicar durante todo o filme. A cena final é a primeira vez que os dois são honestos um com o outro, e já é tarde para o relacionamento.",
    sceneAndQuote: "Cena final: vendem o apartamento. Pela primeira vez são honestos. Pedem desculpas. Resolvem, mas não reatam.\nFala: 'Eu acho que me tornei uma pessoa que eu não gosto muito quando estou com você.' — Brooke",
    platform: "Prime Video: 'Separados pelo Casamento' — últimos 10 minutos",
    videoLink: "",
    hook: "Por que a honestidade que salvaria chegou só quando já não havia mais nada para salvar?",
    clinicalAngle: "Às vezes a separação não é o fim. É o primeiro momento em que os dois conseguiram ser reais. A pergunta é: por que não antes?",
  },
  {
    theme: "THE_CHOICE",
    order: 3,
    characters: "Charlie & Nicole",
    type: "Filme",
    work: "História de um Casamento (2019) · Netflix",
    context: "A mediação é a primeira cena do filme. O casamento já acabou antes do espectador entender por quê. O que Nicole escreveu sobre Charlie só aparece no final.",
    sceneAndQuote: "Abertura do filme: a mediadora pede que os dois leiam o que escreveram um sobre o outro. Nicole para de tentar. Charlie não consegue começar. Vão embora antes de tentar.\nSem fala: é o silêncio de Nicole fechando o caderno que diz tudo.",
    platform: "Netflix: 'História de um Casamento' — primeiros 15 minutos",
    videoLink: "youtube.com/watch?v=lprJ3LAvFbI (legendado PT-BR — mediação nos primeiros 15min)",
    hook: "A primeira chance de salvar esse casamento foi abandonada antes de começar. Você já fez isso?",
    clinicalAngle: "Por que é tão difícil dizer em voz alta o que a gente sente, mesmo quando há espaço para isso? A mediação não falhou. Os dois desistiram antes dela.",
  },
  {
    theme: "THE_CHOICE",
    order: 4,
    characters: "Cindy & Dean",
    type: "Filme",
    work: "Blue Valentine (2010) · YouTube / Dailymotion",
    context: "Depois de ver o início apaixonado durante todo o filme, o público chega ao final sabendo exatamente o que se perdeu. A cena final mostra um que ainda quer e outro que já decidiu.",
    sceneAndQuote: "Cena final: Dean implora para Cindy ficar. Ela sai. Ele sobe para o terraço e vê os fogos sozinho. Os créditos voltam para a cena do ukelele.\nFala: 'Por favor. Fica. Nós podemos consertar isso.' — Dean",
    platform: "YouTube (dublado PT): youtube.com/watch?v=bwUgBD9b4Nc\nDailymotion (legendado): dailymotion.com/video/x22ng2w",
    videoLink: "youtube.com/watch?v=bwUgBD9b4Nc (dublado PT — últimos 5min)\ndailymotion.com/video/x22ng2w (legendado completo)",
    hook: "Há momentos em que um ainda quer e o outro já tomou a decisão por dentro. Como você sabe a diferença?",
    clinicalAngle: "Há momentos em que um ainda quer e o outro já foi, mesmo estando presente. O que separa 'podemos consertar' de 'não há mais nada para consertar'?",
  },
  {
    theme: "THE_CHOICE",
    order: 5,
    characters: "Fleabag",
    type: "Série",
    work: "Fleabag T2 (2019) · Prime Video",
    context: "Mulher britânica sem nome que usa humor e ironia para não se aproximar de ninguém de verdade. O Padre da segunda temporada é a primeira pessoa que insiste em vê-la, e ela não sabe o que fazer com isso.",
    sceneAndQuote: "T2 E4: o Padre pergunta o que ela quer de verdade. Ela hesita. Faz piada. Ele insiste. Ela responde.\nFala: 'Eu só quero que alguém me diga o que vestir de manhã.' — Fleabag",
    platform: "Prime Video: 'Fleabag' — T2 episódio 4",
    videoLink: "youtube.com/watch?v=GnC3VY3Ltqg (cena do confessionário T2 legendada)\nyoutube.com/watch?v=ivaDiIkTBno (melhores momentos legendados)",
    hook: "Quando foi a última vez que você se permitiu querer algo de verdade, sem transformar em piada antes que machucasse?",
    clinicalAngle: "A piada como defesa. A ironia como distância. A independência que parece força mas é solidão bem embrulhada.",
  },
  {
    theme: "CONTROL_ROMANTICIZED",
    order: 1,
    characters: "Edward & Bella",
    type: "Filme",
    work: "Crepúsculo (2008) · Prime Video / Netflix",
    context: "Saga consumida por uma geração inteira de mulheres jovens. O 'Twilight Renaissance' do TikTok em 2020 trouxe mulheres 25-38 de volta para questionar o que a saga ensinou sobre amor.",
    sceneAndQuote: "Cena do quarto (~55min): Edward revela que ficou assistindo Bella dormir sem ela saber. Música suave, rosto dela sorrindo. O roteiro apresenta como romântico.\nFala: 'Eu vim aqui toda noite nos últimos meses.' — Edward. Ela sorri.",
    platform: "Prime Video: 'Crepúsculo' — cena: ~55 minutos\nNetflix: 'Crepúsculo'",
    videoLink: "",
    hook: "E se tudo que te ensinaram que era amor não fosse?",
    clinicalAngle: "A gente aprendeu que cuidado e controle têm a mesma cara quando embalados com música bonita. O que te ensinaram que era amor quando você tinha 15 anos, e o que você pensa disso hoje?",
  },
  {
    theme: "CONTROL_ROMANTICIZED",
    order: 2,
    characters: "Chuck & Blair",
    type: "Série",
    work: "Gossip Girl · Max",
    context: "Chuck e Blair são os personagens mais populares da série, shippados por anos. O público que cresceu defendendo esse casal hoje revisita com olhos diferentes.",
    sceneAndQuote: "T1 E7: Chuck força beijo em Blair enquanto ela tenta ir embora. O roteiro apresenta como icônico e romântico. Fãs ainda defendem: 'é diferente porque é Chuck e Blair.'\nFala: 'Você é minha. E eu sou seu. Isso sempre foi verdade.' — Chuck",
    platform: "Max: 'Gossip Girl' — T1 episódio 7",
    videoLink: "",
    hook: "O que faz a gente chamar de paixão o que seria inaceitável em qualquer outro contexto?",
    clinicalAngle: "Quando a embalagem muda, a beleza, o dinheiro, o drama, o que a gente chama de amor pode mudar também. A cena é a mesma. O que muda é quem está assistindo.",
  },
  {
    theme: "CONTROL_ROMANTICIZED",
    order: 3,
    characters: "Hardin & Tessa",
    type: "Filme",
    work: "After (saga 2019-2022) · Prime Video",
    context: "Saga com base de fãs ativa no Brasil, especialmente mulheres 18-30. O ciclo instabilidade-reconciliação é o padrão central dos quatro filmes.",
    sceneAndQuote: "Depois da descoberta da aposta: Hardin vai ao apartamento de Tessa, chora, pede perdão. Ela volta. O ciclo se repete em todos os filmes.\nFala: 'Eu sei que fiz coisas horríveis. Mas ninguém vai te amar como eu amo.' — Hardin",
    platform: "Prime Video: 'After' — primeira meia hora",
    videoLink: "",
    hook: "Quando o pedido de desculpa vira parte do ciclo, ele ainda conta como arrependimento?",
    clinicalAngle: "O ciclo de machuca e reconcilia não é intensidade. É um padrão. O pedido de desculpa que vem depois do machucado não apaga o padrão. O que apaga?",
  },
  {
    theme: "MASCULINE_VULNERABILITY",
    order: 1,
    characters: "Ted Lasso",
    type: "Série",
    work: "Ted Lasso T2 (2021) · Apple TV+",
    context: "Técnico americano eternamente otimista e gentil. O público o conhece como o homem mais gentil da televisão. Ninguém esperava vê-lo vulnerável. Muito compartilhado por mulheres com parceiros.",
    sceneAndQuote: "T2 E10: Ted tem ataque de pânico durante um jogo. Em vez de esconder, vai ao psicólogo. Primeira vez que um homem nesse papel pede ajuda, sem que isso seja fraqueza.\nFala: 'Acho que eu preciso de ajuda.' — Ted Lasso",
    platform: "Apple TV+: 'Ted Lasso' — T2 episódio 10",
    videoLink: "",
    hook: "Três palavras que custam muito para um homem dizer. O que impede?",
    clinicalAngle: "Por que é tão difícil para um homem dizer que precisa de ajuda? O que a gente ensina os homens sobre sentir, e como isso aparece dentro do casamento?",
  },
  {
    theme: "MASCULINE_VULNERABILITY",
    order: 2,
    characters: "Don Draper",
    type: "Série",
    work: "Mad Men T4 · Prime Video",
    context: "Publicitário de sucesso com identidade falsa e casamentos que afundam. Incapaz de ser real com quem ama. O público o conhece como o homem mais infeliz de sucesso da televisão.",
    sceneAndQuote: "T4 E7: Don chora ao saber de uma morte. O momento mais real que ele já teve foi com Peggy, a colega, não com a esposa.\nFala: 'Você é a única pessoa que conheço que sabe que não me conhece.' — Don para Peggy",
    platform: "Prime Video: 'Mad Men' — T4 episódio 7",
    videoLink: "",
    hook: "Ele consegue sentir. Só não consegue sentir com a esposa. Por quê?",
    clinicalAngle: "Não é incapacidade de intimidade. É incapacidade com a pessoa errada. O que o casamento exige que esse homem não consegue dar?",
  },
  {
    theme: "IDEALIZATION",
    order: 1,
    characters: "Jesse & Celine",
    type: "Filme",
    work: "Before Sunrise (1995) · Aluguel digital",
    context: "Americano e francesa que se conhecem num trem e passam uma única noite conversando. O público os conhece como o casal romântico por excelência, e esquece que esse é o momento em que ainda não se conhecem de verdade.",
    sceneAndQuote: "Cabine de disco (~40min): os dois fingem ligar para amigos imaginários para se dizer o que não conseguem dizer diretamente. A conexão é real, mas ainda é uma projeção.\nFala: 'Se alguém pudesse me ver agora... estaria com inveja?' — Jesse e Celine",
    platform: "Aluguel: Google Play ou Apple TV (legendado)",
    videoLink: "",
    hook: "Você se apaixonou pela pessoa, ou pela versão dela que você criou na cabeça?",
    clinicalAngle: "No início a gente fala com a versão que quer que o outro seja, não com quem ele é. Quando começamos a ver a pessoa real, e quando isso muda o amor?",
  },
  {
    theme: "IDEALIZATION",
    order: 2,
    characters: "Tom Hansen",
    type: "Filme",
    work: "(500) Dias com Ela (2009) · Disney+",
    context: "Designer gráfico que se apaixona por Summer, ou pela versão que criou dela. O filme é narrado do ponto de vista dele. Summer deixou claro desde o início que não queria relacionamento sério. O público tende a culpá-la. Esse é exatamente o ponto.",
    sceneAndQuote: "Cena expectativa x realidade (~1h): mostra lado a lado o que Tom imaginou e o que aconteceu de verdade.\nFala: 'Você não acredita no amor?' / 'Acredito. Só não acredito que ele seja pra mim.' — Summer",
    platform: "Disney+: '(500) Dias com Ela'",
    videoLink: "Buscar: '500 Days of Summer expectation vs reality scene'\nBuscar: '500 Dias com Ela cena expectativa realidade legendado'",
    hook: "Você já estava num relacionamento que só existia na sua cabeça?",
    clinicalAngle: "Tom não foi enganado. Ele escolheu não ouvir. A gente às vezes se apaixona pela versão que criou, não pela pessoa que está na frente. E quando a realidade aparece, chama de traição.",
  },
  {
    theme: "LOVE_AS_PERMANENCE",
    order: 1,
    characters: "Hyun-woo & Hae-in",
    type: "Série",
    work: "Rainha das Lágrimas (2024) · Netflix",
    context: "Herdeira rica e marido humilde que se afastaram e estavam em processo de divórcio. O diagnóstico de Hae-in muda tudo. Hyun-woo escolhe ficar sem ela pedir. Maior série coreana da Netflix em 2024.",
    sceneAndQuote: "E14: Hae-in tem pouco tempo de vida e não conta. Hyun-woo descobre por outros meios. A abraça sem dizer que sabe. Os dois choram juntos sem falar uma palavra.\nFala: 'Eu não vou a lugar nenhum.' — Hyun-woo",
    platform: "Netflix: 'Rainha das Lágrimas' — episódio 14",
    videoLink: "",
    hook: "O que é o amor quando você não pode mais fazer nada, só ficar?",
    clinicalAngle: "O amor como ato de permanência. Quando não há mais nada para resolver, só há como estar. O que fica quando tudo o que era fácil acabou?",
  },
  {
    theme: "LOVE_AS_PERMANENCE",
    order: 2,
    characters: "Georges & Anne",
    type: "Filme",
    work: "Amour (2012) · MUBI / aluguel",
    context: "Professores de música aposentados, casados há décadas. O derrame de Anne muda tudo. Georges cuida dela até o fim. O público cinéfilo os conhece pela Palma de Ouro, o filme mais doloroso sobre o que o amor exige.",
    sceneAndQuote: "Café da manhã depois do derrame: Georges serve o café, Anne fica olhando para nada. Ele espera. O roteiro não explica, só mostra o peso do cuidado real.\nFala: 'Eu não vou te mandar para um asilo.' — Georges",
    platform: "MUBI: 'Amour'\nAluguel: Google Play ou Apple TV",
    videoLink: "",
    hook: "E se o amor verdadeiro não for o que você sente, mas o que você escolhe fazer quando não sente nada?",
    clinicalAngle: "O amor despido de romantismo: presente, pesado, real. O que fica quando estar junto deixa de ser prazeroso e vira só real? Quantos relacionamentos sobreviveriam a isso?",
  },
] as const;
