import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import type { InsightStatus } from "@prisma/client";

// GET /api/portal/insights?engagementId=X&status=PENDING
// Admin/Manager: lista insights por engagement.
// Cliente do portal: só APPROVED do próprio engagement.
export async function GET(req: NextRequest) {
  const session = (await getServerSession(authOptions)) as any;
  if (!session) return NextResponse.json({ error: "Não autorizado" }, { status: 401 });

  const engagementId = req.nextUrl.searchParams.get("engagementId");
  if (!engagementId) {
    return NextResponse.json({ error: "engagementId obrigatório" }, { status: 400 });
  }

  const role = session.user?.role;
  const userId = session.user?.id as string;

  const engagement = await prisma.clientEngagement.findUnique({
    where: { id: engagementId },
    select: { id: true, clientId: true },
  });
  if (!engagement) return NextResponse.json({ error: "Engagement não encontrado" }, { status: 404 });

  const isAdmin = role === "ADMIN" || role === "MANAGER";
  const isOwner = engagement.clientId === userId;
  if (!isAdmin && !isOwner) {
    return NextResponse.json({ error: "Acesso negado" }, { status: 403 });
  }

  const statusParam = req.nextUrl.searchParams.get("status") as InsightStatus | null;

  // Cliente do portal só vê APPROVED, sem outros filtros
  const status: InsightStatus | undefined = isAdmin
    ? (statusParam ?? undefined)
    : "APPROVED";

  const insights = await prisma.clientInsight.findMany({
    where: {
      engagementId,
      ...(status ? { status } : {}),
    },
    orderBy: [{ status: "asc" }, { createdAt: "desc" }],
  });

  return NextResponse.json(insights);
}

// POST /api/portal/insights — cria insight manual (admin escreve do zero)
export async function POST(req: NextRequest) {
  const session = (await getServerSession(authOptions)) as any;
  if (!session) return NextResponse.json({ error: "Não autorizado" }, { status: 401 });
  const role = session.user?.role;
  if (role !== "ADMIN" && role !== "MANAGER") {
    return NextResponse.json({ error: "Acesso negado" }, { status: 403 });
  }

  const body = await req.json().catch(() => ({}));
  const { engagementId, category, severity, title, body: text } = body as any;

  if (!engagementId || !title || !text) {
    return NextResponse.json(
      { error: "engagementId, title e body são obrigatórios" },
      { status: 400 },
    );
  }

  const created = await prisma.clientInsight.create({
    data: {
      engagementId,
      category: category || "CUSTOM",
      severity: severity || "INFO",
      status: "APPROVED", // insight manual já entra aprovado
      title,
      body: text,
      autoGenerated: false,
      approvedById: session.user.id,
      approvedAt: new Date(),
    },
  });

  return NextResponse.json(created);
}
