import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import {
  getAccountInsights,
  getAdInsightsForAccount,
} from "@/lib/meta/api";
import {
  buildMetaSummary,
  aggregateMetaSummaries,
} from "@/lib/meta/resolvers";
import { generateInsights, type AdForInsight } from "@/lib/insights/generator";

// POST /api/portal/insights/generate
// Body: { engagementId: string, datePreset?: string }
// Roda o rules engine no summary + ads Meta atuais e salva os candidatos
// como ClientInsight com status=PENDING. Retorna os criados.
//
// Skipa duplicatas: se já existe um insight PENDING ou APPROVED com o mesmo
// (category, title) nas últimas 14 dias, não cria de novo — evita entulho.
export async function POST(req: NextRequest) {
  const session = (await getServerSession(authOptions)) as any;
  if (!session) return NextResponse.json({ error: "Não autorizado" }, { status: 401 });
  const role = session.user?.role;
  if (role !== "ADMIN" && role !== "MANAGER") {
    return NextResponse.json({ error: "Acesso negado" }, { status: 403 });
  }

  const body = await req.json().catch(() => ({}));
  const { engagementId, datePreset = "last_30d" } = body as any;
  if (!engagementId) {
    return NextResponse.json({ error: "engagementId obrigatório" }, { status: 400 });
  }

  const engagement = await prisma.clientEngagement.findUnique({
    where: { id: engagementId },
    select: { id: true },
  });
  if (!engagement) return NextResponse.json({ error: "Engagement não encontrado" }, { status: 404 });

  const accounts = await prisma.metaAdAccount.findMany({
    where: { engagementId, hidden: false },
    include: { connection: { select: { accessToken: true, status: true } } },
  });
  const active = accounts.filter((a) => a.connection.status === "ACTIVE");
  if (active.length === 0) {
    return NextResponse.json({ created: 0, note: "Nenhuma conta Meta ativa nesse engagement." });
  }

  try {
    const perAccountSummaries: ReturnType<typeof buildMetaSummary>[] = [];
    const allAds: AdForInsight[] = [];
    let currency = "BRL";

    for (const acc of active) {
      const [accountInsights, adsInsights] = await Promise.all([
        getAccountInsights(acc.connection.accessToken, acc.accountId, datePreset),
        getAdInsightsForAccount(acc.connection.accessToken, acc.accountId, datePreset, 300).catch(() => [] as any[]),
      ]);
      perAccountSummaries.push(buildMetaSummary(accountInsights));
      if (acc.currency) currency = acc.currency;

      for (const ad of adsInsights) {
        const sum = buildMetaSummary(ad);
        allAds.push({
          adId: ad.ad_id,
          adName: ad.ad_name,
          hookRate: sum.hookRate,
          holdRate: sum.holdRate,
          thruPlayRate: sum.thruPlayRate,
          video3SecWatched: sum.video3SecWatched,
          spend: sum.spend,
          costPerResult: sum.costPerResult,
          results: sum.results,
        });
      }
    }

    const summary = aggregateMetaSummaries(perAccountSummaries);
    const candidates = generateInsights({ summary, ads: allAds, currency });

    // Anti-duplicata — não cria se já existe (category, title) nos últimos 14 dias
    const cutoff = new Date(Date.now() - 14 * 24 * 60 * 60 * 1000);
    const existing = await prisma.clientInsight.findMany({
      where: {
        engagementId,
        createdAt: { gte: cutoff },
        status: { in: ["PENDING", "APPROVED"] },
      },
      select: { category: true, title: true },
    });
    const key = (c: string, t: string) => `${c}::${t}`;
    const existingKeys = new Set(existing.map((e) => key(e.category, e.title)));

    const toCreate = candidates.filter((c) => !existingKeys.has(key(c.category, c.title)));

    const created = await prisma.$transaction(
      toCreate.map((c) =>
        prisma.clientInsight.create({
          data: {
            engagementId,
            category: c.category,
            severity: c.severity,
            status: "PENDING",
            title: c.title,
            body: c.body,
            autoGenerated: true,
            sourceMetric: c.sourceMetric,
            meta: (c.meta as any) || {},
          },
        }),
      ),
    );

    return NextResponse.json({
      candidates: candidates.length,
      created: created.length,
      skipped: candidates.length - created.length,
      items: created,
    });
  } catch (e: any) {
    return NextResponse.json(
      { error: `Falha ao gerar insights: ${e.message || "desconhecido"}` },
      { status: 500 },
    );
  }
}
