-- Fundação do dashboard por tipo de cliente:
--   1. BusinessType (INFOPRODUCT | ECOMMERCE | SERVICES) no ClientEngagement
--   2. ClientInsight — curadoria de análise (sistema sugere → admin aprova)
--   3. ClientDashboardConfig — filtros salvos + métricas custom por engagement

-- ─── 1. BusinessType ─────────────────────────────────────────
CREATE TYPE "BusinessType" AS ENUM ('INFOPRODUCT', 'ECOMMERCE', 'SERVICES');

ALTER TABLE "ClientEngagement"
  ADD COLUMN "businessType" "BusinessType" NOT NULL DEFAULT 'SERVICES';

CREATE INDEX "ClientEngagement_businessType_idx"
  ON "ClientEngagement"("businessType");

-- Semeadura por tipo de frente existente (EngagementType)
-- STRATEGY costuma ser Serviços/consultivo → SERVICES (default já cobre)
-- PAID_TRAFFIC pode ser qualquer coisa — deixa SERVICES e o admin edita
-- LANDING_PAGE + GMB tendem a ser SERVICES também → default já cobre
-- Se algum cliente já é infoproduto ou e-commerce, atualiza manualmente depois.

-- ─── 2. ClientInsight ────────────────────────────────────────
CREATE TYPE "InsightCategory" AS ENUM (
  'VIDEO', 'BUDGET', 'GEO', 'HEALTH', 'CREATIVE', 'FUNNEL', 'CUSTOM'
);

CREATE TYPE "InsightSeverity" AS ENUM ('OK', 'WARN', 'INFO');

CREATE TYPE "InsightStatus" AS ENUM ('PENDING', 'APPROVED', 'DISMISSED');

CREATE TABLE "ClientInsight" (
  "id"             TEXT PRIMARY KEY,
  "engagementId"   TEXT NOT NULL REFERENCES "ClientEngagement"("id") ON DELETE CASCADE,
  "category"       "InsightCategory" NOT NULL,
  "severity"       "InsightSeverity" NOT NULL DEFAULT 'INFO',
  "status"         "InsightStatus"   NOT NULL DEFAULT 'PENDING',
  "title"          TEXT NOT NULL,
  "body"           TEXT NOT NULL,
  "autoGenerated"  BOOLEAN NOT NULL DEFAULT true,
  "sourceMetric"   TEXT,
  "meta"           JSONB NOT NULL DEFAULT '{}'::jsonb,
  "approvedById"   TEXT,
  "approvedAt"     TIMESTAMP,
  "dismissedAt"    TIMESTAMP,
  "createdAt"      TIMESTAMP NOT NULL DEFAULT NOW(),
  "updatedAt"      TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX "ClientInsight_engagementId_status_idx"
  ON "ClientInsight"("engagementId", "status");

CREATE INDEX "ClientInsight_status_createdAt_idx"
  ON "ClientInsight"("status", "createdAt" DESC);

-- ─── 3. ClientDashboardConfig ────────────────────────────────
CREATE TABLE "ClientDashboardConfig" (
  "id"                 TEXT PRIMARY KEY,
  "engagementId"       TEXT NOT NULL UNIQUE REFERENCES "ClientEngagement"("id") ON DELETE CASCADE,
  "customMetrics"      JSONB NOT NULL DEFAULT '[]'::jsonb,
  "defaultDateRange"   TEXT NOT NULL DEFAULT 'last_30d',
  "comparePeriod"      TEXT NOT NULL DEFAULT 'previous',
  "createdAt"          TIMESTAMP NOT NULL DEFAULT NOW(),
  "updatedAt"          TIMESTAMP NOT NULL DEFAULT NOW()
);
